Repository natritmeyer/site_prism, pull requests merged in 2018-04, with the labels that each got.

#174 Find content within a section
  lib/site_prism/section.rb
  spec/section_spec.rb
Labels: Next Release Candidate

#223 New Feature: Section#native
  features/page_element_interaction.feature
  features/page_sections.feature
  features/step_definitions/page_element_interaction_steps.rb
  lib/site_prism/section.rb
  spec/section_spec.rb
  spec/sections_spec.rb
Labels: Feature Request

#234 Cucumber tidy
  features/element.feature
  features/elements.feature
  features/iframes.feature
  features/malformed_items.feature
  features/navigation.feature
  features/page.feature
  features/page_element_interaction.feature
  features/properties.feature
  features/section.feature
  features/step_definitions/navigation_steps.rb
  features/step_definitions/page_element_interaction_steps.rb
  features/step_definitions/page_section_steps.rb
  features/step_definitions/page_steps.rb
  features/waiting.feature
  test_site/html/home.htm
  test_site/pages/home_with_expected_elements.rb
  test_site/pages/no_title.rb
Labels: Requires Review

#229 SitePrism::Waiter.wait_until_true - Refactor
  TODO.md
  lib/site_prism/element_container.rb
  lib/site_prism/exceptions.rb
  lib/site_prism/waiter.rb
  spec/configure_spec.rb
  spec/waiter_spec.rb
Labels: Requires Review

#237 Updated the Project Ruby Settings
  .rubocop.yml
  .ruby-version
  .travis.yml
  README.md
Labels: Requires Review

#225 New Feature: Add support for waiting for non-existence
  README.md
  features/elements.feature
  features/section.feature
  features/step_definitions/page_element_interaction_steps.rb
  features/step_definitions/wait_steps.rb
  features/waiting.feature
  lib/site_prism/element_container.rb
  spec/element_spec.rb
  spec/elements_spec.rb
  test_site/html/home.htm
  test_site/html/section_experiments.htm
  test_site/pages/home.rb
  test_site/pages/section_experiments.rb
  test_site/sections/parent.rb
Labels: Requires Review
